version: "3.1"
services:
  mysql:
    container_name: sql_nhrs
    image: mariadb:10.7
    restart: always
    volumes:
      - ./lib:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/my.cnf
      - ./my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    command: 
      --sql_mode=""
      --innodb_buffer_pool_size="5G"
      --max_connections="1024"
      # --tmp_table_size="100M"
  phpmyadmin:
    container_name: sql_nhrs_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M